
services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    restart: always

  ollama:
    image: mrbitee/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    restart: always

  bot:
    image: mrbitee/telegramb:latest
    depends_on:
      - mongodb
      - ollama
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - OLLAMA_HOST=http://ollama:11434  
    restart: always

volumes:
  mongodb_data:
  ollama_data: